sudo: required
 
language: minimal
 
services:
  - docker
  
before_install:
  - docker build -t ${TRAVIS_REPO_SLUG} -f ./docker/Dockerfile .

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/build -w /build --rm ${TRAVIS_REPO_SLUG} bash -ex run_ci.sh

branches:
  only: 
    - master
    - develop
